### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.geeksville.location.SkyLinesTrackingWriter.emitPosition(long, double, double, float, int, float, float[], float)' on a null object reference

### ISSUE THREAD

**Issue by ubx** [ubx/SkyLinesTracker#11]
```bash
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.geeksville.location.SkyLinesTrackingWriter.emitPosition(long, double, double, float, int, float, float[], float)' on a null object reference
	at ch.luethi.skylinestracker.PositionService.onLocationChanged(PositionService.java:101)
	at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:281)
	at android.location.LocationManager$ListenerTransport.access$000(LocationManager.java:210)
	at android.location.LocationManager$ListenerTransport$2.handleMessage(LocationManager.java:233)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.os.HandlerThread.run(HandlerThread.java:61)

```

**Comment by ubx** [comment]
Fixed in branch queue.
