### ISSUE TITLE
java.lang.RuntimeException: Unable to stop service ch.luethi.skylinestracker.PositionService@401f28a0: java.lang.NullPointerException

### ISSUE THREAD

**Issue by ubx** [ubx/SkyLinesTracker#12]
```bash
java.lang.RuntimeException: Unable to stop service ch.luethi.skylinestracker.PositionService@401f28a0: java.lang.NullPointerException
	at android.app.ActivityThread.handleStopService(ActivityThread.java:2086)
	at android.app.ActivityThread.access$2900(ActivityThread.java:117)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1001)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:130)
	at android.app.ActivityThread.main(ActivityThread.java:3687)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:507)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
	at ch.luethi.skylinestracker.PositionService.onDestroy(PositionService.java:79)
	at android.app.ActivityThread.handleStopService(ActivityThread.java:2069)
	... 10 more

```

**Comment by ubx** [comment]
Fixed in branch queue.
