### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke interface method 'long ch.luethi.skylinestracker.FixQueueIF.size()' on a null object reference

### ISSUE THREAD

**Issue by ubx** [ubx/SkyLinesTracker#18]
```bash
java.lang.NullPointerException: Attempt to invoke interface method 'long ch.luethi.skylinestracker.FixQueueIF.size()' on a null object reference
	at ch.luethi.skylinestracker.MainActivity$2.onReceive(MainActivity.java:204)
	at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
	at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
	at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:241)
	at android.app.ActivityThread.main(ActivityThread.java:6217)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

```

**Comment by ubx** [comment]
commit ae9c6adb51323187a0b996fd5c6e6c5d42d9cffb
