### ISSUE TITLE
java.lang.RuntimeException: Unable to start service ch.luethi.skylinestracker.PositionService@6c6e671 with Intent { cmp=ch.luethi.skylinestracker/.PositionService (has extras) }: java.lang.SecurityException: "gps" location provider requires ACCESS_FINE_LOCATION permission.

### ISSUE THREAD

**Issue by ubx** [ubx/SkyLinesTracker#20]
```bash
java.lang.RuntimeException: Unable to start service ch.luethi.skylinestracker.PositionService@6c6e671 with Intent { cmp=ch.luethi.skylinestracker/.PositionService (has extras) }: java.lang.SecurityException: "gps" location provider requires ACCESS_FINE_LOCATION permission.
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3314)
	at android.app.ActivityThread.-wrap21(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1565)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6077)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
Caused by: java.lang.SecurityException: "gps" location provider requires ACCESS_FINE_LOCATION permission.
	at android.os.Parcel.readException(Parcel.java:1683)
	at android.os.Parcel.readException(Parcel.java:1636)
	at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:614)
	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:887)
	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:503)
	at ch.luethi.skylinestracker.PositionService.startLocationUpdates(PositionService.java:144)
	at ch.luethi.skylinestracker.PositionService.onStartCommand(PositionService.java:126)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3297)
	... 8 more

```

**Comment by ubx** [comment]
Ignored, do to testing.
